run:
  modules-download-mode: readonly
  timeout: 3m
linters:
  disable-all: true
  enable:
    - errcheck
    - exportloopref
    - gochecknoinits
    - gofmt
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - revive
    - staticcheck
    - typecheck
    - unparam
    - unused
issues:
  exclude:
    - Using the variable on range scope `tc` in function literal
  max-issues-per-linter: 0
  max-same-issues: 0
